# -*- mode: ruby -*-
# vi: set ft=ruby :

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|

  config.vm.box = "ubuntu/trusty32"

  config.vm.box_url = "https://vagrantcloud.com/ubuntu/boxes/trusty32/versions/14.04/providers/virtualbox.box"
  
  config.vm.provision "shell", path: "install.sh"
  
end
