# -*- mode: ruby -*-
# vi: set ft=ruby :

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  
  # The virtual machine box name
  config.vm.box = "ubuntu/trusty32"
  
  # The virtual machine box URL. Vagrant will download the virtual machine image from this address.
  config.vm.box_url = "https://vagrantcloud.com/ubuntu/boxes/trusty32/versions/14.04/providers/virtualbox.box"
  
  # The following line configures how Vagrant provisions the virtual machine. In other words, what
  # Vagrant does in order to complete the virtual machine installation. Here we are telling Vagrant
  # to run the script called "install.sh" on the virtual machine console.
  config.vm.provision "shell", path: "install.sh"
  
  # Sets the VM name for Vagrant
  config.vm.define "zeroToJava" do |zeroToJava|
  end
  
  # Configures the virtual machine provider (also known as the hypervisor).
  config.vm.provider "virtualbox" do |v|

    # If true, starts the VM using a graphical window.
    v.gui = false

    # The VM name for VirtualBox
    v.name = "zeroToJava"

  end
  
end
